import { Bai_Jamjuree, Roboto, Roboto_Flex as roboto } from 'next/font/google'
import './globals.css'
const roboto = Roboto({ subsets: ['latin'] variable:'--font-roboto'})
const Bai_Jamjuree = bai_Jamjuree({ subsets: ['latin'],weight'700',variable:'font--bai--jamjuree'  })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})          {
  return (
          <html lang="en">
      <body className={`${roboto.variable} ${Bai_Jamjuree.variable} font-sans`}>{children}</body>
        </html>
)
}
